/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LeaguesLeagueIdImport } from './routes/leagues/$leagueId'
import { Route as DraftsDraftIdImport } from './routes/drafts/_.$draftId'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const LeaguesLeagueIdScoresLazyImport = createFileRoute(
  '/leagues/$leagueId/scores',
)()
const LeaguesLeagueIdRankingsLazyImport = createFileRoute(
  '/leagues/$leagueId/rankings',
)()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const LeaguesLeagueIdRoute = LeaguesLeagueIdImport.update({
  path: '/leagues/$leagueId',
  getParentRoute: () => rootRoute,
} as any)

const LeaguesLeagueIdScoresLazyRoute = LeaguesLeagueIdScoresLazyImport.update({
  path: '/scores',
  getParentRoute: () => LeaguesLeagueIdRoute,
} as any).lazy(() =>
  import('./routes/leagues/$leagueId/scores.lazy').then((d) => d.Route),
)

const LeaguesLeagueIdRankingsLazyRoute =
  LeaguesLeagueIdRankingsLazyImport.update({
    path: '/rankings',
    getParentRoute: () => LeaguesLeagueIdRoute,
  } as any).lazy(() =>
    import('./routes/leagues/$leagueId/rankings.lazy').then((d) => d.Route),
  )

const DraftsDraftIdRoute = DraftsDraftIdImport.update({
  path: '/drafts/$draftId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/leagues/$leagueId': {
      id: '/leagues/$leagueId'
      path: '/leagues/$leagueId'
      fullPath: '/leagues/$leagueId'
      preLoaderRoute: typeof LeaguesLeagueIdImport
      parentRoute: typeof rootRoute
    }
    '/drafts//$draftId': {
      id: '/drafts//$draftId'
      path: '/drafts/$draftId'
      fullPath: '/drafts/$draftId'
      preLoaderRoute: typeof DraftsDraftIdImport
      parentRoute: typeof rootRoute
    }
    '/leagues/$leagueId/rankings': {
      id: '/leagues/$leagueId/rankings'
      path: '/rankings'
      fullPath: '/leagues/$leagueId/rankings'
      preLoaderRoute: typeof LeaguesLeagueIdRankingsLazyImport
      parentRoute: typeof LeaguesLeagueIdImport
    }
    '/leagues/$leagueId/scores': {
      id: '/leagues/$leagueId/scores'
      path: '/scores'
      fullPath: '/leagues/$leagueId/scores'
      preLoaderRoute: typeof LeaguesLeagueIdScoresLazyImport
      parentRoute: typeof LeaguesLeagueIdImport
    }
  }
}

// Create and export the route tree

interface LeaguesLeagueIdRouteChildren {
  LeaguesLeagueIdRankingsLazyRoute: typeof LeaguesLeagueIdRankingsLazyRoute
  LeaguesLeagueIdScoresLazyRoute: typeof LeaguesLeagueIdScoresLazyRoute
}

const LeaguesLeagueIdRouteChildren: LeaguesLeagueIdRouteChildren = {
  LeaguesLeagueIdRankingsLazyRoute: LeaguesLeagueIdRankingsLazyRoute,
  LeaguesLeagueIdScoresLazyRoute: LeaguesLeagueIdScoresLazyRoute,
}

const LeaguesLeagueIdRouteWithChildren = LeaguesLeagueIdRoute._addFileChildren(
  LeaguesLeagueIdRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/leagues/$leagueId': typeof LeaguesLeagueIdRouteWithChildren
  '/drafts/$draftId': typeof DraftsDraftIdRoute
  '/leagues/$leagueId/rankings': typeof LeaguesLeagueIdRankingsLazyRoute
  '/leagues/$leagueId/scores': typeof LeaguesLeagueIdScoresLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/leagues/$leagueId': typeof LeaguesLeagueIdRouteWithChildren
  '/drafts/$draftId': typeof DraftsDraftIdRoute
  '/leagues/$leagueId/rankings': typeof LeaguesLeagueIdRankingsLazyRoute
  '/leagues/$leagueId/scores': typeof LeaguesLeagueIdScoresLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/leagues/$leagueId': typeof LeaguesLeagueIdRouteWithChildren
  '/drafts//$draftId': typeof DraftsDraftIdRoute
  '/leagues/$leagueId/rankings': typeof LeaguesLeagueIdRankingsLazyRoute
  '/leagues/$leagueId/scores': typeof LeaguesLeagueIdScoresLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/leagues/$leagueId'
    | '/drafts/$draftId'
    | '/leagues/$leagueId/rankings'
    | '/leagues/$leagueId/scores'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/leagues/$leagueId'
    | '/drafts/$draftId'
    | '/leagues/$leagueId/rankings'
    | '/leagues/$leagueId/scores'
  id:
    | '__root__'
    | '/'
    | '/leagues/$leagueId'
    | '/drafts//$draftId'
    | '/leagues/$leagueId/rankings'
    | '/leagues/$leagueId/scores'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  LeaguesLeagueIdRoute: typeof LeaguesLeagueIdRouteWithChildren
  DraftsDraftIdRoute: typeof DraftsDraftIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  LeaguesLeagueIdRoute: LeaguesLeagueIdRouteWithChildren,
  DraftsDraftIdRoute: DraftsDraftIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/leagues/$leagueId",
        "/drafts//$draftId"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/leagues/$leagueId": {
      "filePath": "leagues/$leagueId.tsx",
      "children": [
        "/leagues/$leagueId/rankings",
        "/leagues/$leagueId/scores"
      ]
    },
    "/drafts//$draftId": {
      "filePath": "drafts/_.$draftId.tsx"
    },
    "/leagues/$leagueId/rankings": {
      "filePath": "leagues/$leagueId/rankings.lazy.tsx",
      "parent": "/leagues/$leagueId"
    },
    "/leagues/$leagueId/scores": {
      "filePath": "leagues/$leagueId/scores.lazy.tsx",
      "parent": "/leagues/$leagueId"
    }
  }
}
ROUTE_MANIFEST_END */
